apiVersion: v1
kind: Service
metadata:
  name: simple-market-app-frontend
  namespace: kube-system
  labels:
    app: simple-market-app-frontend
    node: sanchezkubenode
spec:
  ports:
  - name: "3030"
    port: 3030
    targetPort: 3000
  selector:
    app: simple-market-app-frontend
    name: react
  type: NodePort