apiVersion: v1
kind: Service
metadata:
  name: simple-market-app-frontend
  namespace: kube-system
  labels:
    app: simple-market-app-frontend
    node: sanchezkubenode
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: react
      name: react
  selector:
    app: simple-market-app-frontend
    name: react